# https://stackoverflow.com/questions/72943637/dockerizing-a-fastapi-backend-with-react-frontend-tips
version: 3.8
services:
  backend:
    env_file:
      - backend/.env
    build:
      context: ./backend
      dockerfile: ./DockerFile
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    expose:
      - 8000

  frontend:
    env_file:
      - frontend/.env
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
      restart: always
      ports:
        - 127.0.0.1:3006:3006
      expose:
        -3000