version: '3.9'
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
    ports:
      - "8000:8000"
    expose:
      - 8000
    volumes:
      - ./backend:/app
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
    environment:
      - REACT_APP_API_URL=http://backend:8000/api
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
    ports:
      - "3000:3000"
    expose:
      - 3000
    volumes:
      - ./frontend:/app
    networks:
      - my_network